services:
  mongo:
    container_name: versus-mongo
    image: mongo:4.4.18
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DBNAME}
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

  server:
    container_name: versus-server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: versus-server:latest
    env_file: .env
    environment:
      DATA_PATH: /app/data
      PUBLIC_PATH: /app/public
      DOCS_PATH: /app/docs
    volumes:
      - ./server/src:/app/src
      - ./data:/app/data
      - ./frontend/dist/spa:/app/public:ro
      - ./site:/app/docs:ro
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    restart: unless-stopped

  docs:
    container_name: versus-docs
    image: squidfunk/mkdocs-material
    volumes:
      - .:/docs
    ports:
      - "8001:8000"
    profiles:
      - docs
    command: serve --dev-addr=0.0.0.0:8000
