version: '3'
services:
  mongo:
    container_name: versus-mongo
    image: "mongo:4.0"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_PASSWORD}"
      MONGO_INITDB_DATABASE: "${MONGODB_DBNAME}"
    volumes:
      - ./var/mongo/data/:/data/db/
      - ./var/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "${MONGODB_PORT}:27017"
