POST {{host}}/ytdl
Accept: application/json
Content-Type: application/json
Authorization: Basic {{login}} {{password}}

{
  "urlOrigin": "https://www.youtube.com/watch?v=TZ2p40DtwZE&ab_channel=MeekKelly",
  "forceDownload": true
}

###
